
package com.test4javadev.pashkouski.soap;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DateWebService", targetNamespace = "http://soap.pashkouski.test4javadev.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DateWebService {


    /**
     * 
     * @return
     *     returns com.test4javadev.pashkouski.soap.LocalDateTime
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDate", targetNamespace = "http://soap.pashkouski.test4javadev.com/", className = "com.test4javadev.pashkouski.soap.GetDate")
    @ResponseWrapper(localName = "getDateResponse", targetNamespace = "http://soap.pashkouski.test4javadev.com/", className = "com.test4javadev.pashkouski.soap.GetDateResponse")
    public LocalDateTime getDate();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStringDate", targetNamespace = "http://soap.pashkouski.test4javadev.com/", className = "com.test4javadev.pashkouski.soap.GetStringDate")
    @ResponseWrapper(localName = "getStringDateResponse", targetNamespace = "http://soap.pashkouski.test4javadev.com/", className = "com.test4javadev.pashkouski.soap.GetStringDateResponse")
    public String getStringDate();

}
