
package com.test4javadev.pashkouski.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapDateProducer", targetNamespace = "http://soap.pashkouski.test4javadev.com/", wsdlLocation = "http://127.0.0.1:8085/dateproducer/soap/DateWebService?wsdl")
public class SoapDateProducer
    extends Service
{

    private final static URL SOAPDATEPRODUCER_WSDL_LOCATION;
    private final static WebServiceException SOAPDATEPRODUCER_EXCEPTION;
    private final static QName SOAPDATEPRODUCER_QNAME = new QName("http://soap.pashkouski.test4javadev.com/", "SoapDateProducer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8085/dateproducer/soap/DateWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPDATEPRODUCER_WSDL_LOCATION = url;
        SOAPDATEPRODUCER_EXCEPTION = e;
    }

    public SoapDateProducer() {
        super(__getWsdlLocation(), SOAPDATEPRODUCER_QNAME);
    }

    public SoapDateProducer(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPDATEPRODUCER_QNAME, features);
    }

    public SoapDateProducer(URL wsdlLocation) {
        super(wsdlLocation, SOAPDATEPRODUCER_QNAME);
    }

    public SoapDateProducer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPDATEPRODUCER_QNAME, features);
    }

    public SoapDateProducer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapDateProducer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DateWebService
     */
    @WebEndpoint(name = "SoapDateProducerPort")
    public DateWebService getSoapDateProducerPort() {
        return super.getPort(new QName("http://soap.pashkouski.test4javadev.com/", "SoapDateProducerPort"), DateWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DateWebService
     */
    @WebEndpoint(name = "SoapDateProducerPort")
    public DateWebService getSoapDateProducerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.pashkouski.test4javadev.com/", "SoapDateProducerPort"), DateWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPDATEPRODUCER_EXCEPTION!= null) {
            throw SOAPDATEPRODUCER_EXCEPTION;
        }
        return SOAPDATEPRODUCER_WSDL_LOCATION;
    }

}
